namespace DailyMachineSpirit.Functions.Pages;

/// <summary>The frame around every page: head, skip link, header and navigation, footer, and the toast region.</summary>
public static class Layout
{
    private const string SiteName = "The Daily Machine Spirit";

    // Without the script the seal can't be broken, so the truth simply shows, and the copy buttons, which need it, hide.
    private const string NoScriptCss = ".truth[hidden]{display:block}.seal,[data-copy]{display:none}";

    // Every page but Today, which has the masthead instead.
    private const string Brand = $"<a class=\"brand\" href=\"/\">{Svg.BrandCog}{SiteName}</a>";

    /// <param name="title">The page's own title, or empty for Today, whose title is the site's name.</param>
    /// <param name="description">Plain text for search results and link previews.</param>
    public static string Page(string title, string description, Section section, string main)
    {
        var fullTitle = title.Length == 0 ? SiteName : $"{title} · {SiteName}";
        return $"""
            <!doctype html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>{Html.Encode(fullTitle)}</title>
            <meta name="description" content="{Html.Encode(description)}">
            <meta property="og:site_name" content="{SiteName}">
            <meta property="og:title" content="{Html.Encode(title.Length == 0 ? SiteName : title)}">
            <meta property="og:description" content="{Html.Encode(description)}">
            <meta property="og:type" content="website">
            <meta name="theme-color" content="#100e0b">
            <link rel="preload" href="/fonts/cinzel.woff2" as="font" type="font/woff2" crossorigin>
            <link rel="preload" href="/fonts/eb-garamond.woff2" as="font" type="font/woff2" crossorigin>
            <style>{Styles.Css}</style>
            <noscript><style>{NoScriptCss}</style></noscript>
            </head>
            <body>
            <a class="skip" href="#main">Skip to content</a>
            <div class="page">
            <header class="site-header">
            {(section == Section.Today ? string.Empty : Brand)}
            <nav aria-label="Main">
            <a href="/"{Current(section == Section.Today)}>Today</a>
            <a href="/archive"{Current(section == Section.Archive)}>Archive</a>
            </nav>
            </header>
            <main id="main" tabindex="-1">
            {main}
            </main>
            <footer class="site-footer">
            <p class="motto">Knowledge is lost. The rituals remain.</p>
            <p class="disclaimer">An unofficial fan satire, not affiliated with or endorsed by Games Workshop. Warhammer 40,000 and related names are trademarks of Games Workshop Ltd. Prayers are generated by AI.</p>
            </footer>
            </div>
            <div class="toast-region" role="status" aria-live="polite"></div>
            <script>{Script.Js}</script>
            </body>
            </html>
            """;
    }

    private static string Current(bool isCurrent) => isCurrent ? " aria-current=\"page\"" : string.Empty;
}
